name: test

on:
 repository_dispatch:
 workflow_dispatch:
  push:
    tags:
      - v1.**

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - x86_64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@go1.20
        env:
          ARCH: ${{ matrix.arch }}-openwrt-22.03
          FEEDNAME: packages_ci
          PACKAGES: luci-theme-argonne
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Create a Release ipk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
          token: ${{ secrets.ACCESS_TOKEN }}
          commit: master
          tag: v1.${{ github.run_number }}${{ matrix.arch }}
